### ISSUE TITLE
Rare "crash" with RPG Series mods

### ISSUE THREAD

**Issue by ghost** [BeansGalaxy/BeansBackpacks#8]
Well, today I decide to install rpg series mods to play Wizards in particular, until I got disconnected from my world after I died with /kill (other forms of died in the game work as well to produce the "crash") and I dont know if the problem is beans backpacks or Wizards rpg series but there is the log of the game with these mods together. I think Trinkets involves this rare issue.

[latest.log](https://github.com/BeansGalaxy/BeansBackpacks/files/13789375/latest.log)

**Comment by BeansGalaxy** [comment]
Its a problem with my mod and Trinkets. Looking through Emi's code I don't think our mods are compatible because of the way I store the player's inventory. 
I'm just about to release the beta for v2 and it _might_ be compatible because I save my inventory data completely different than before, but it's the beta and will still be buggy.

**Comment by BeansGalaxy** [comment]
Solved ***soo*** long ago, everything is working now :)
